### ISSUE TITLE
Rename LM3-PPA to BiomeE

### ISSUE THREAD

**Issue by stineb** [computationales/rsofun#107]
Following the conversation with @wengensheng: To avoid confusion with non-OA developments within GFDL and their LM3 model (now at LM4), we should avoid using ‘LM3-PPA’ as a model name. Within rsofun, several file names, functions, and references in the documentation now use the name ‘LM3-PPA’. We should replace all these uses of ‘LM3-PPA' with ‘BiomeE’.

**Comment by khufkens** [comment]
Run `devtools::document()` to run the documentations.

Also check the build checks locally, which should reflect those online (https://github.com/computationales/rsofun/actions/runs/3549850089/jobs/5962668922) stating that vignettes were not adjusted. Not sure if you did a `sed` replacement or a manual.

**Comment by khufkens** [comment]
Per https://github.com/computationales/rsofun/issues/108

The format of NEWS.md is:
```
# the lastest version

- changes
- changes

# the earlier version

- changes
- changes
```

see `rpmodel` https://github.com/computationales/rpmodel
