### ISSUE TITLE
Link of logo

### ISSUE THREAD

**Issue by stineb** [computationales/rsofun#109]
On our rsofun website, when clicking on the GECO logo, it's linked to [https://computationales.ethz.ch/](https://computationales.ethz.ch/) . This should be changed to our group website, eventually to be hosted at [geco-group.org](http://geco-group.org/).

**Comment by khufkens** [comment]
Website theme changes to the navbar are made here:
https://github.com/computationales/GECO_template/blob/main/inst/pkgdown/templates/navbar.html
