### ISSUE TITLE
GPP issues lm3ppa pmodel

### ISSUE THREAD

**Issue by khufkens** [computationales/rsofun#42]
When plotting this line using a p-model run.

https://github.com/computationales/rsofun/blob/e6ec7c59774d412a2ad2c0b38dd2635cb3b4ca69/src/gpp_lm3ppa.mod.f90#L319

I get values of this magnitude: 237404.172

If run with gs_leuning and plotting this line (equivalent?):
https://github.com/computationales/rsofun/blob/e6ec7c59774d412a2ad2c0b38dd2635cb3b4ca69/src/gpp_lm3ppa.mod.f90#L168

Values are of this magnitude:  6.87971863E-05

This suggests that something is off an order of magnitudes, with the most likely candidate PPFD.

The p-model requires (mol m-2 s-1) where gs_leuning uses ?

It remains uncertain how these large values lead to less vegetation and smaller cohorts (which are ultimately killed). Large GPP values should lead to crazy allocation and growth I would assume.

**Comment by khufkens** [comment]
Things to check:

- [ ] Input drivers (daily values)
- [ ] fast / slow steps of the model
- [ ] cohort triggers - killing trees
- [ ] ...

**Comment by wengensheng** [comment]
Hi, Koen,
"gs_leuning" assumes the radiation input is "short-wave radiation" (w/m2).
Then, it converts it to PAR by a factor 0.0000046. see the conversion codes
below:
  ! Convert Solar influx from W/(m^2s) to mol_of_quanta/(m^2s) PAR,
  ! empirical relationship from McCree is light=rn*0.0000046
  light_top = rad_top*rad_phot
  par_net   = rad_net*rad_phot
I think you either comment out these two lines (421, 422), or convert PAR
to radiation before calling gs_leuning if you want to keep it intact.

Best,
Ensheng

**Comment by khufkens** [comment]
Dark respiration factor forgotten in the p-model and should read:

```
myrd  = fapar_tree * out_pmodel%vcmax25 * gpp%rd_to_vcmax * rd_ calc_ftemp_inst_rd( forcing%Tair - kTkelvin ) 
```

wrong units due to inclusion of step_seconds in the gpp calculation

https://github.com/computationales/rsofun/blob/76b9f593d7627d58939fc956856ffaf6f1f4ca1b/src/gpp_lm3ppa.mod.f90#L319

```
mygpp = fapar_tree * out_pmodel%lue * myppfd
```

step seconds needs to be removed

**Comment by khufkens** [comment]
Hi @wengensheng 

Beni figured it out, as suspected it seems to be a unit issue - wrong interpretation due to the change from hourly to daily time step which was missed in the p-model formulation. The rest of the units seem ok.

Respiration also missed a scaling factor, this meant that respiration was mostly larger than assimilation and stuff died. This is now fixed and things look more ok-ish. @stineb will cross check still. But this seems to be almost resolved.

Thanks for all the input!

**Comment by stineb** [comment]
Closed as per issue [49](https://github.com/computationales/rsofun/issues/49).
