### ISSUE TITLE
gpp_obs correct

### ISSUE THREAD

**Issue by stineb** [computationales/rsofun#48]
This here is renamed 
```
    rename(
      'gpp_obs' = 'gpp'
    )
```
[here](https://github.com/computationales/rsofun/blob/b9a63cf81563e54f0854c17b10697c3d6171f367/R/cost_functions.R#L50)

Does this make sense? Is it observations, not modelled?

**Comment by khufkens** [comment]
Probably should be `gpp_mod`, just can't be gpp as you merge with obs which has a similar variable.

**Comment by khufkens** [comment]
fixed
https://github.com/computationales/rsofun/commit/a646715276649a015be735d4b10c43eb4117b511
