### ISSUE TITLE
Make forcings consistent for lm3ppa and pmodel setups

### ISSUE THREAD

**Issue by stineb** [computationales/rsofun#54]
Make consistent such that the forcing data frame (variable names, units) now used for the P-model setup, can also be used for the lm3ppa setup (except that `fapar` is not used in the lm3ppa setup)

**Comment by khufkens** [comment]
pmodel | lm3ppa
-- | --
date |  -
year | YEAR
doy | DOY
hour | HOUR
temp | TEMP
temp_soil | SoilT
prec | RAIN
snow |  -
vpd |  -
rh | RH
ppfd | Swdown
par | PAR
patm | PRESSURE
wind | WIND
ccov_int |  -
ccov |  -
co2 | aCO2_AW
swc | SWC

**Comment by khufkens** [comment]
![Screenshot from 2022-03-16 15-50-50](https://user-images.githubusercontent.com/1354258/158618275-cd30e77f-6316-417e-8761-77d4e8f4ab9d.png)

**Comment by khufkens** [comment]
Fixed as per:
https://github.com/computationales/rsofun/commit/672631c9927a5c6e86298f2afc44c38990fe5810

`vpd` is not back filled for now as not used by LM3PPA
