### ISSUE TITLE
Documentation of arguments and return variables

### ISSUE THREAD

**Issue by stineb** [computationales/rsofun#88]
The driver object used as argument to rsofun contains a lot of quantities that are nowhere really documented (meaning, units). 
Man page info for all functions should be complemented with info about all required variables, their names, and their units.
Explanations may also go into vignette [`pmodel_use.Rmd`](https://computationales.github.io/rsofun/articles/pmodel_use.html), explaining the [demo data](https://computationales.github.io/rsofun/articles/pmodel_use.html#demo-data), and into vignette [`prepare_forcing`](https://computationales.github.io/rsofun/articles/prepare_forcing.html).

**Comment by khufkens** [comment]
This is technically an {ingestr} issue.

For this and other reasons of brittleness I would like to move away from ingestr, for at least the operational parts of data generation as we can't guarantee consistent workflows in ingestr - too  many moving parts. This will move into FluxDataKit, other use cases are more difficult, but also more difficult to justify.

**Comment by khufkens** [comment]
Just a note this the documentation side, not the enforcement side of the units.

**Comment by pepaaran** [comment]
I just noticed that the output variables of `runread_pmodel_f()` are not described in detail in the documentation. This is a ToDo!
