### ISSUE TITLE
Cost functions for calibration routine

### ISSUE THREAD

**Issue by pepaaran** [computationales/rsofun#93]
**Hard-coded simulation parameters**
In some of the cost functions for parameter calibration that we have in use, the values of the model parameters that are kept fixed are hard coded. For example:

  params_modl <- list(
    kphio           = par[[1]],
    soilm_par_a     = 1.0,
    soilm_par_b     = 0.0,
    tau_acclim_tempstress = 10,
    par_shape_tempstress  = 0.0
  )

The issue that this creates is that we'll be optimizing for a set of parameters that may not coincide with the ones used for the actual P-model simulations, and if there is a dependence among the parameter values we'll be using the wrong optimization objective. Hence, we should
- Allow the non-calibrated parameters to take the values passed as argument. (Always?)
- Include a verification step that makes sure all simulation parameters are present before calling run_pmodel_f_bysite().
- Write a check such that parameters are in a biologically sensible range. For this we need to agree on what those ranges are. (Does this already exist?)
 

**Non-existent simulation parameters - purge**

Some of the current cost functions use parameters that are not used in the P-model simulations (e.g. vpdstress). Some other functions aren't even functions, just comment lines. We should delete obsolete functions and keep only the ones that are i) used and correct, or ii) fairly general and a good example for future users.

**Inconsistent cost function arguments**

Ultimately there should be one single structure for the cost functions, with the same arguments and internal structure, that meets the quality checks we agree on. In order to allow some flexibility, we could make some arguments mandatory and others up to the user, while fitting int he `calib_sofun()` framework. Currently, some cost functions have an additional argument `par_names` or don't include all of the basic arguments (in general, we're using `par`, `obs`, `drivers` and `inverse`).
`GenSA()` only requires that the first argument of cost_*() be the vector of parameters over which minimization is to take place. For `BayesianTools` we only need  a cost function that allows to compute a "likelihood" from it and returns just a scalar.

**Comment by khufkens** [comment]
We pass BRC / FULL / ORG parameters in the settings list so we can make one function which switches for those base settings I think, limiting the hard coded parameters to only one cost function (rather than having to split things externally by setup.

Keep GenSA, it is generally fast and pretty reliable when conditionality isn't a strong constraint - also less complex and less likely to be a breaking dependency (e.g. BT). It remains simulated annealing so the voodoo factor is a bit higher than BT but good for first quick exploration.

**Comment by pepaaran** [comment]
I have some questions:

So if I understood correctly, you would like a cost function that takes `par` and `setup` as arguments? Or would you rather modify `calib_sofun()` such that it takes `setup` as a parameter (ORG / FULL / BRC) rather than taking a cost function? The first option would leave more flexibility for the future, but I think both options are possible while fixing the non-calibrated parameter values.

From Stocker et al. 2020 GMD, I don't understand very well the difference between ORG and BRC. What I got is that the quatum yield efficiency (kphio) doesn't depend on the temperature in ORG and it does depend on temperature in BRC. To my understanding, FULL calibrates `kphio`, `soilm_par_a` and `soilm_par_b`, keeping the tempstress parameters fixed, while both ORG and BRC keep everything except `kphio` fixed and calibrates `kphio`. So how can the difference between ORG and BRC be specified through a cost function? Was the ORG setting simulated differently for the paper?

When you refer to GenSA and BayesianTools, are you thinking of using RMSE as metric for both optimization methods? Or do you want to use RMSE for GenSA only and an appropriate likelihood for BayesianTools? 

Another topic: Can we get rid of the `inverse` parameter? I think if we explicitly document that cost functions are meant to be maximized with BayesianTools, we don't need that parameter anymore.

Thanks!

**Comment by khufkens** [comment]
I would do the former, pass a parameter like you do with "inverse". This requires the least amount of bookkeeping.

You can keep parameters constant by defining them as such (allowing no variability during optimization, despite being flexible (user defined, i.e. not hard coded).

I would retain one RMSE based GenSA approach, although I think this should work on BT as well, and one max. likelihood approach for BT. This should have things covered.

**Comment by khufkens** [comment]
I would do the former, pass a parameter like you do with "inverse". This requires the least amount of bookkeeping.

You can keep parameters constant by defining them as such (allowing no variability during optimization, despite being flexible (user defined, i.e. not hard coded).

I would retain one RMSE based GenSA approach, although I think this should work on BT as well, and one max. likelihood approach for BT. This should have things covered.
