### ISSUE TITLE
compilation failed for package 'rsofun'

### ISSUE THREAD

**Issue by jrmodel** [computationales/rsofun#94]
I successfully downloaded gfrotran and install the rsofun package. However, when I tried to build and install the packages, it didn't work.

It always requires me to install the Rtools. Even if I have installed R tools, it always say" building R packages requires additional build tools"

**Comment by jrmodel** [comment]
For Rstduio, it needs tools to compile code including Fortran, C++
(1) Please use the specific rtools version, it depends on your versison of R language
(2) C:\rtools40\mingw64\bin. It's the location of gfortran in rtools. Please add the location into the environmental variable.

**Comment by khufkens** [comment]
You should set your environmental variables yourself. This can not be done by R or the package provider (due to the variety of setups). Code passes unit checks and built checks on all major platforms, so this is system dependent.
