### ISSUE TITLE
Nested dataframe errors

### ISSUE THREAD

**Issue by pepaaran** [computationales/rsofun#96]
There is a data.frame nested in a list, nested in another list in the `runread_pmodel_f` output. This was causing the tidyr::unnest() issues. I believe it's caused by the fix of issue #77  (this [commit](https://github.com/computationales/rsofun/commit/a4c07f2bd42156873d0596aac0b37a6c7209458d#commitcomment-88904390)) and can be easily fixed by reverting the change. The code below explains the problem:

```{r}
library(rsofun); library(purrr); library(tidyr)

p_model_drivers
?run_pmodel_f_bysite

params_modl <- list(
  kphio           = 0.09423773,
  soilm_par_a     = 0.33349283,
  soilm_par_b     = 1.45602286,
  tau_acclim_tempstress = 10,
  par_shape_tempstress  = 0.0
)

## Run chunk from runread_pmodel_f
purrr::pmap(p_model_drivers, run_pmodel_f_bysite,par=params_modl, makecheck=TRUE)
# The output is a list with one element, rather than a data frame

## Create drivers with two rows
p_model_drivers2 <- add_row(p_model_drivers, p_model_drivers)
p_model_drivers2$sitename[2] <- "FR-Pue2" # Change name
p_model_drivers2$forcing[[2]]$temp <- p_model_drivers2$forcing[[2]]$temp +1
# increase temp to have different results and compare later

p_model_drivers2


## check the output structure when there's more rows in drivers
purrr::pmap(p_model_drivers2, run_pmodel_f_bysite,par=params_modl, makecheck=TRUE) 
# By the way, for this we're taking the same parameters for all the sites
# The output is a list with two data frames! Which is what we would expect,
# if the output resembles p_model_validation

# Now run exactly what's on runread_pmodel_f()
output2 <- p_model_drivers2 %>% 
  dplyr::mutate(
    data = list(
      purrr::pmap(.,
                  run_pmodel_f_bysite,
                  par = params_modl,
                  makecheck = TRUE
      )
    )
  ) %>% 
  dplyr::select(sitename, site_info, data)

## Check structure of output2
output2
output2 %>% filter(sitename=="FR-Pue") %>% unnest(data) 
# For one row, we unnest two rows because there were two data frames per row in the data column
output2$data[[1]][[1]] == output2$data[[2]][[1]] # Saving the same results for two different sites
```

Reverting the aforementioned commit may break things depending on the structure of the ingested data. Hence, we need to have tests for the package that have data from two sites (or doubled up like above, to keep the package <5MB) with correct structure. I'm not aware of their existence. Also, once FluxDataKit is ready, we should take the outputs created there as the standard input to rsofun. @khufkens

**Comment by khufkens** [comment]
@pepaaran I'm putting together some FluxDataKit data for testing today, as I won't progress until I can confirm this works for some sites. The formatting is consistent so ideally it should work. Alas, especially the tidyverse parts are fickle and very version specific at times it seems.

I would propose that, as far as possible, we remove all tidyverse constructs as they seem prone to idiosyncratic issues.

**Comment by khufkens** [comment]
This is fixed by: https://github.com/computationales/rsofun/pull/112
